---

- hosts: laptop
  become: yes
  become_method: sudo

  vars:
    user: achtmhz
    user_group: achtmhz
    hostname: mordoror
    user_home: /home/{{ user }}
    venv_home: "{{ user_home }}/venv"

  pre_tasks:
    - name: rename host
      hostname: name={{ hostname }}

  roles:
    - { role: setup-user, tags: ['setup'] }
    - { role: system-tools, tags: ['systools'] }
    - { role: dev-tools, tags: ['devtools'] }
    - { role: devops, tags: ['ops'] }
    - { role: java-dev, tags: ['java'] }
    - { role: py-dev, tags: ['python'] }
    - { role: py-data-analysis, tags: ['pydata'] }
    - { role: stats-learning, tags: ['stats'] }
    - { role: cloud-aws, tags: ['aws'] }
