---

- hosts: laptop
  sudo: yes

  vars:
    user: achtmhz
    hostname: mordoror
    venv_home: /home/{{ user }}

  tasks:
    - name: add terminator repo
      apt_repository: repo='ppa:gnome-terminator'
    - name: install terminator
      apt: name=terminator update_cache=yes state=latest

    - name: install user tools
      apt: name={{ item }} state=present
      with_items:
       - git
       - meld
       - zsh
       - htop
       - screen
       - tmux

    - name: rename host
      hostname: name={{ hostname }}
    - name: create groups
      group: name={{ user }} state=present
    - name: create user
      user: name={{ user }} shell=/bin/zsh groups={{ user }} state=present

    - name: copy bash aliases
      copy: src=./files/aliases dest=/home/{{ user }}/.bash_aliases owner={{ user }} group={{ user }} mode=0644
    - name: copy vi .exrc
      copy: src=./files/exrc dest=/home/{{ user }}/.exrc owner={{ user }} group={{ user }} mode=0644

    - name: install common linux packages
      apt: name={{ item }} state=latest
      with_items:
       - vagrant
       - build-essential

  roles:
    - py-dev
    - py-data-analysis
    - java-dev


# get oh-my zsh installed but chsh fails
# try with sudo sh -c "..."
- hosts: laptop
  vars:
    - user: achtmhz
  sudo_user: "{{ user }}"
  sudo: yes

  tasks:
    - name: oh-my zsh
      shell: sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

