---

- hosts: laptop
  become: yes
  become_method: sudo

  vars:
    user: achtmhz
    user_group: achtmhz
    hostname: mordoror
    user_home: /home/{{ user }}
    venv_home: "{{ user_home }}"

  pre_tasks:
    - name: rename host
      hostname: name={{ hostname }}

  tasks:
    - name: data analysis
      apt: name={{ item }} state=latest
      with_items:
       - r-base
       - r-base-dev
       - octave

    - name: aws command line interface
      pip: name=awscli state=latest

  roles:
    - { role: setup-user, tags: ['setup'] }
    - { role: system-tools, tags: ['systools'] }
    - { role: dev-tools, tags: ['devtools'] }
    - { role: devops, tags: ['ops'] }
    - { role: py-dev, tags: ['python'] }
    - { role: py-data-analysis, tags: ['pydata'] }
    - { role: java-dev, tags: ['java'] }
