---

# ubuntu laptop

- name: install linux packages
  yum: name={{ item }} state=present
  with_items:
   - ansible
   - vagrant
   - maven
   - htop
   - zsh
   - python-virtualenv
   - python-pip

- name: create virtualenv for analysis
  virtualenv: 

- name: install analysis packages into virtualenv
  pip: name={{ item }}
  with_items:
   - bottleneck
   - numpy
   - scipy
   - scikit-learn
   - seaborn
   - luigi
   - IPython

