---

- hosts: laptop
  sudo: yes

  vars:
    user: achtmhz
    hostname: mordoror

  tasks:
    - name: install user tools
      apt: name={{ item }} state=present
      with_items:
       - htop
       - zsh

    - name: rename host
      hostname: name={{ hostname }}
    - name: create groups
      group: name={{ user }} state=present
    - name: create user
      user: name={{ user }} shell=/bin/zsh groups={{ user }} state=present

    - name: copy bash aliases
      copy: src=./files/aliases dest=/home/{{ user }}/.bash_aliases owner={{ user }} group={{ user }} mode=0644
    - name: copy vi .exrc
      copy: src=./files/exrc dest=/home/{{ user }}/.exrc owner={{ user }} group={{ user }} mode=0644

    - name: install linux packages
      apt: name={{ item }} state=latest
      with_items:
       - ansible
       - vagrant
       - maven
       - build-essential
       - python-virtualenv
       - python-pip
       - python-dev

    - name: install analysis packages into virtualenv
      pip: name={{ item }} state=latest
      with_items:
       - nose
       - sqlalchemy

    - name: install numpy linux packages
      apt: name={{ item }} state=present
      with_items:
       - libblas-dev
       - liblapack-dev

    - name: install scipy linux packages
      apt: name={{ item }} state=present
      with_items:
       - gfortran 

    - name: install scikit-learn linux packages
      apt: name={{ item }} state=present
      with_items:
       - libpng-dev
       - libfreetype6-dev
       - pkg-config

    - name: install analysis packages into virtualenv
      pip: name={{ item }} state=latest
      with_items:
       - numpy
       - scipy
       - bottleneck
       - scikit-learn
       - pandas
       - seaborn
       - IPython
       - luigi
