---

- hosts: default
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: install linux packages
      apt: name={{ item }} state=present
      with_items:
       - ansible
       - vagrant
       - maven
       - htop
       - zsh
       - python-virtualenv
       - python-pip

    - name: install analysis packages into virtualenv
      pip: name={{ item }}
      with_items:
       - bottleneck
       - numpy
       - scipy
       - scikit-learn
       - seaborn
       - luigi
       - IPython
