---

- hosts: laptop
  become: yes
  become_method: sudo

  vars:
    user: achtmhz
    user_group: achtmhz
    hostname: mordoror
    user_home: /home/{{ user }}
    venv_home: "{{ user_home }}"

  pre_tasks:
    - name: add terminator repo
      apt_repository: repo='ppa:gnome-terminator'
      tags: terminator

    - name: install terminator
      apt: name=terminator update_cache=yes state=latest
      tags: terminator

    - name: install user tools
      apt: name={{ item }} state=present
      with_items:
       - zsh
       - htop
       - sysstat
       - iptraf
       - etherape
       - tree
       - screen
       - tmux

    - name: rename host
      hostname: name={{ hostname }}

    - name: create group
      group: name={{ user }} state=present
    - name: create user
      user: name={{ user }} shell=/bin/zsh groups={{ user }} state=present
    - name: create bin folder
      file: path={{ user_home }}/bin owner={{ user }} group={{ user_group }} state=directory

  tasks:
    - name: data analysis
      apt: name={{ item }} state=latest
      with_items:
       - r-base
       - r-base-dev
       - octave

    - name: aws command line interface
      pip: name=awscli state=latest

  roles:
    - dev-tools
    - devops
    - py-dev
    #- py-data-analysis
    - java-dev


# got oh-my zsh installed but chsh fails
# try with sudo sh -c "..."
- hosts: laptop
  vars:
    user: achtmhz
  become_user: "{{ user }}"
  become_method: sudo

  tasks:
    - name: copy bash aliases
      copy: src=./files/aliases dest=/home/{{ user }}/.bash_aliases owner={{ user }} group={{ user }} mode=0644
    - name: copy vi .exrc
      copy: src=./files/exrc dest=/home/{{ user }}/.exrc owner={{ user }} group={{ user }} mode=0644

    - name: oh-my zsh
      shell: sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

