---

- hosts: default
  remote_user: vagrant
  sudo: yes

  tasks:
    - name: add ansible repo
      apt_repository: repo="ppa:ansible/ansible"
      tags: ansible_latest

    - name: install ansible latest
      apt: name=ansible update_cache=yes state=latest
      tags: ansible_latest

