---

- name: install py-dev linux packages
  apt: name={{ item }} state=latest
  with_items:
   - python-virtualenv
   - python-pip
   - python-dev
   - python-pygments

# support the oh-my-zsh virutalenvwrapper plugin
# => automagically activates the venv when a git repo directory is entered 
- name: install virutalenvwrapper
  pip: name=virtualenvwrapper state=latest
  tags: venvwrapper

# first idea was to place a venv-wrapper.zsh in the .oh-my-zsh/custom folder
# but the oh-my-zsh virtualenvwrapper plugin runs source on virutalenvwrapper.sh
# so config has to happen before the plugin is loaded
- name: configure virtualenvwrapper
  lineinfile: dest=/home/{{ user }}/.zshrc
        insertbefore="^plugins"
        line="export WORKON_HOME={{ venv_home }}"
        state=present
  tags: venvwrapper

# TODO
# foreach python git repo create the venv with the same name
- name: create venv
  shell: source /home/{{ user }}/.zshrc; mkvirtualenv pydev
         executable=/usr/bin/zsh
  become_user: "{{ user }}"
  become_method: sudo
  tags: venvwrapper

# install packages required by project
# pip -r requirements.txt
- name: install py-dev packages into venv_home
  pip: name={{ item }}
       virtualenv={{ venv_home }}/pydev
       state=latest
  with_items:
   - nose
   - pyvows
   - inject
   - sqlalchemy
   - agnostic
  become_user: "{{ user }}"
  become_method: sudo
